# Generated by Django 2.2.14 on 2020-08-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdetails',
            name='account_balance',
            field=models.CharField(default='0', max_length=10, verbose_name='Account Balance'),
        ),
    ]
