# Generated by Django 2.2.14 on 2020-08-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP_Auth', '0002_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
